### ISSUE TITLE
Demo site generate 502 error

### ISSUE THREAD

**Issue by yingjin-us** [Azure/cortana-intelligence-product-detection-from-images#5]
http://cntkimages.azurewebsites.net/ generated 502 error

**Comment by lixzhang** [comment]
It was just fixed. Thanks for reporting.

**Comment by yingjin-us** [comment]
Can you share with me the fix? My site experienced similar problem. Would increase startUpTimeLimit in web.config work?

**Comment by lixzhang** [comment]
Was your site working before? If so, can you try restarting your web app from the Azure portal? That’s how I fixed the problem.

**Comment by yingjin-us** [comment]
No. After follow the instruction of deploying web service, the site always
gave service unavailable 503 error as shown beloe

**Comment by yingjin-us** [comment]
Also in the log file under wwwroot/logs directory on Azure, the error
message is
--------------------------------------------------------------------------------------------------------------
PARAMETERS: datasetName = grocery
Traceback (most recent call last):
  File "D:\home\site\wwwroot\WebApp\runserver.py", line 2, in <module>
    from model import *
  File "D:\home\site\wwwroot\WebApp\model.py", line 20, in <module>
    import config
ImportError: No module named 'config'

**Comment by lixzhang** [comment]
Do you see the config.py file in the "web_service/WebApp" folder?

**Comment by yingjin-us** [comment]
No. Is it the same one as the one in data-management folder?

**Comment by lixzhang** [comment]
Did you run the following before deploying the web service? 

cd <path-to-data_management-folder>
activate cntk-py35
python 5_copy_web_service_data.py

**Comment by yingjin-us** [comment]
Hi, Lixun,
Thank you very much for your quick response.
Yes, I did that step. But somehow config.py wasn't copied over.
But your insight still helps. I manually copied that file to Azure site and
my site is working now.
Thank you very much.
Ying
